### ISSUE TITLE
Add Github CI for Running all Tests

### ISSUE THREAD

**Issue by ariel-frischer** [ai-christianson/RA.Aid#54]
Had an issue where, resolving a merge conflict broke tests, but did not notice it because of missing CI testing setup.
Will look into adding this. This issue is for tracking/discussions.

**Comment by leonj1** [comment]
Something like this should fix it, but tests are currently broken in master branch :( 
I've fixed the tests here, so wait for that to merge to prevent duplicating test fixes:
https://github.com/ai-christianson/RA.Aid/pull/56

```
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make setup-dev
        
    - name: Run tests
      run: make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
